class DataTypeCases:
    def __init__(self):
        self.data_types = {
            "case_id": str,
            "age": int,
            "gender": str,
            "anxiety_score": int,
            "depression_score": int,
            "sleep_quality": int,
            "stress_level": int,
            "social_support": str,
            "physical_activity": str,
            "main_issue": str,
            "intervention_type": str,
            "intensity": int,
            "weekly_frequency": int,
            "recommendation_text": str,
            "sleep_hours": float,
            "symptom_duration_months": int,
            "gad7_estimate": int,
            "phq9_estimate": int,
            "panic_symptoms": str,
            "concentration_difficulty": str,
            "irritability_level": int,
            "appetite_change": str,
            "prior_treatment": str,
            "current_medication": str,
            "trauma_history": str,
            "substance_use_risk": str,
            "work_or_study_impairment": str,
            "bmi_estimate": float,
            "comorbid_profile": str,
            "clinical_severity": str
        }

        self.new_case = {
            "case_id": "NEW",  # pode ser fictício
            "age": 30,
            "gender": "female",
            "anxiety_score": 8,
            "depression_score": 7,
            "sleep_quality": 5,
            "stress_level": 6,
            "social_support": "low",
            "physical_activity": "low",
            "main_issue": "describes restlessness linked to family conflict and a recent effort to reduce anxiety",
            "intervention_type": "unknown",
            "intensity": 3,
            "weekly_frequency": 2,
            "recommendation_text": "",  # vazio pois será gerado
            "sleep_hours": 6.5,
            "symptom_duration_months": 6,
            "gad7_estimate": 10,
            "phq9_estimate": 9,
            "panic_symptoms": "no",
            "concentration_difficulty": "yes",
            "irritability_level": 5,
            "appetite_change": "stable",
            "prior_treatment": "none",
            "current_medication": "none",
            "trauma_history": "none",
            "substance_use_risk": "low",
            "work_or_study_impairment": "moderate",
            "bmi_estimate": 25.0,
            "comorbid_profile": "none",
            "clinical_severity": "high"
        }